"""
retrieve/cache.py — Semantic query cache using a dedicated ChromaDB collection.

How it works:
  - On each query: embed → cosine search against past queries
  - If nearest past query has cosine similarity >= 0.95 → return its cached answer
  - On miss: answer is generated by the LLM, then stored here for future reuse
  - LRU eviction at CACHE_MAX_ENTRIES (200) prevents unbounded growth

Cache threshold 0.95 (not 0.9 or 0.92):
  - 0.92 returns wrong cached answers for related-but-different questions
    e.g. "how to deploy X" hits cache for "how to configure X"
  - 0.95 restricts hits to near-paraphrases only
"""

import uuid
from collections import OrderedDict
from typing import Optional

import chromadb

from config import Config
from ingest.embedder import embed_query
from utils.logger import get_logger

log = get_logger(__name__)

_client: Optional[chromadb.PersistentClient] = None
_cache_collection = None

# LRU tracker: OrderedDict preserves insertion order
# entry_id → True. Most recent is at the end.
_lru: OrderedDict = OrderedDict()


def _get_cache_collection():
    global _client, _cache_collection
    if _cache_collection is None:
        Config.CHROMA_DIR.mkdir(parents=True, exist_ok=True)
        _client = chromadb.PersistentClient(path=str(Config.CHROMA_DIR))
        _cache_collection = _client.get_or_create_collection(
            name=Config.CACHE_COLLECTION,
            metadata={"hnsw:space": "cosine"},
        )
        # Rebuild LRU from existing entries (preserves order across restarts)
        existing = _cache_collection.get(include=[])
        for entry_id in existing["ids"]:
            _lru[entry_id] = True
        log.info(f"Cache collection ready: {_cache_collection.count()} entries")
    return _cache_collection


def check_cache(query: str) -> Optional[str]:
    """
    Check if a semantically near-identical query has a cached answer.

    Args:
        query: The user's question.

    Returns:
        Cached answer string if similarity >= CACHE_THRESHOLD, else None.
    """
    collection = _get_cache_collection()

    if collection.count() == 0:
        return None

    embedding = embed_query(query)

    results = collection.query(
        query_embeddings=[embedding],
        n_results=1,
        include=["metadatas", "distances"],
    )

    if not results["ids"][0]:
        return None

    distance = results["distances"][0][0]
    similarity = max(0.0, 1.0 - distance)

    if similarity >= Config.CACHE_THRESHOLD:
        entry_id = results["ids"][0][0]
        cached_answer = results["metadatas"][0][0].get("answer", "")

        # Move to end of LRU (most recently used)
        if entry_id in _lru:
            _lru.move_to_end(entry_id)

        log.info(f"Cache HIT (similarity={similarity:.3f}): returning cached answer")
        return cached_answer

    log.info(f"Cache MISS (similarity={similarity:.3f} < {Config.CACHE_THRESHOLD})")
    return None


def store_cache(query: str, answer: str) -> None:
    """
    Store a query-answer pair in the semantic cache.
    Evicts the least recently used entry if at capacity.

    Args:
        query: The original query.
        answer: The generated answer to cache.
    """
    collection = _get_cache_collection()

    # Evict if at capacity
    if collection.count() >= Config.CACHE_MAX_ENTRIES:
        _evict_oldest()

    entry_id = str(uuid.uuid4())
    embedding = embed_query(query)

    collection.upsert(
        ids=[entry_id],
        embeddings=[embedding],
        documents=[query],
        metadatas=[{"answer": answer, "query": query}],
    )

    _lru[entry_id] = True
    log.debug(f"Cached answer ({len(_lru)}/{Config.CACHE_MAX_ENTRIES} entries)")


def _evict_oldest() -> None:
    """Remove the least recently used (oldest) cache entry."""
    if not _lru:
        return
    oldest_id, _ = _lru.popitem(last=False)
    collection = _get_cache_collection()
    try:
        collection.delete(ids=[oldest_id])
        log.debug(f"LRU evicted: {oldest_id}")
    except Exception as e:
        log.warning(f"LRU eviction failed: {e}")


def clear_cache() -> None:
    """Wipe the entire cache. Useful for testing."""
    collection = _get_cache_collection()
    all_ids = collection.get(include=[])["ids"]
    if all_ids:
        collection.delete(ids=all_ids)
    _lru.clear()
    log.info("Cache cleared")